const Routes = {
  LOADING: 'LOADING',

  LOGIN_STACK: 'LOGIN_STACK',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  
  MAIN_APP: 'MAIN_APP', //DRAWER

  APP_INTRO: 'APP_INTRO',

  HOME_STACK: 'HOME_STACK', // HOMESTACK CONTAINER FOR TABS
  HOME_TABS: 'HOME_TABS', //HOME TABS
  ASSOCIATION_HOME_STACK: 'ASSOCIATION_HOME_STACK',

  ASSOCIATION_HOME_SCREEN: 'ASSOCIATION_HOME_SCREEN',
  ASSOCIATION_REQUEST_SCREEN: 'ASSOCIATION_REQUEST_SCREEN',
  ASSOCIATION_REQUEST_DETAIL: 'ASSOCIATION_REQUEST_DETAIL',
  ASSOCIATION_ARCHIEVED_SCREEN: 'ASSOCIATION_ARCHIEVED_SCREEN',
  ASSOCIATION_ARCHIEVED_DETAIL_SCREEN: 'ASSOCIATION_ARCHIEVED_DETAIL_SCREEN',
  ASSOCIATION_ANNOUNCE_SCREEN: 'ASSOCIATION_ANNOUNCE_SCREEN',
  ASSOCIATION_ANNOUNCE_DETAIL_SCREEN: 'ASSOCIATION_ANNOUNCE_DETAIL_SCREEN',
  ASSOCIATION_ANNOUNCE_SEND_OFFER: 'ASSOCIATION_ANNOUNCE_SEND_OFFER',
  ASSOCIATION_SENDOUT_DETAIL_SCREEN: 'ASSOCIATION_SENDOUT_DETAIL_SCREEN',
  ASSOCIATION_SENDOUT_SCREEN: 'ASSOCIATION_SENDOUT_SCREEN',
  ASSOCIATION_SETTINGS_SCREEN: 'ASSOCIATION_SETTINGS_SCREEN',
  ASSOCIATION_GET_ALL_BUILDINGS: 'ASSOCIATION_GET_ALL_BUILDINGS',
  ASSOCIATION_GET_UNIT_LIST: 'ASSOCIATION_GET_UNIT_LIST',
  ASSOCIATION_ADD_BUILDINGS: 'ASSOCIATION_ADD_BUILDINGS',
  ASSOCIATION_EDIT_BUILDING_SCREEN: 'ASSOCIATION_EDIT_BUILDING_SCREEN',
  ASSOCIATION_ADD_UNITS: 'ASSOCIATION_ADD_UNITS',
  ASSOCIATION_UPDATAE_UNITS_SCREEN: 'ASSOCIATION_UPDATAE_UNITS_SCREEN',
  ASSOCIATION_OWNER_DETAIL: 'ASSOCIATION_OWNER_DETAIL',
  ASSOCIATION_OWNER_BUILDINGS_UNITS: 'ASSOCIATION_OWNER_BUILDINGS_UNITS',
  ASSOCIATION_EDIT_OWNER_DETAIL: 'ASSOCIATION_EDIT_OWNER_DETAIL',
  ASSOCIATION_ADD_BUILDINGS_UNITS: 'ASSOCIATION_ADD_BUILDINGS_UNITS',
  ASSOCIATION_EDIT_USER_DETAIL: 'ASSOCIATION_EDIT_USER_DETAIL',
  ASSOCIATION_MANAGE_OWNERS: 'ASSOCIATION_MANAGE_OWNERS',
  ASSOCIATION_REPORT_SCREEN: 'ASSOCIATION_REPORT_SCREEN',
  ASSOCIATION_SEARCH_SCREEN: 'ASSOCIATION_SEARCH_SCREEN',
  ASSOCIATION_ISSUES_REPORTED_DASHBOARD_SCREEN: 'ASSOCIATION_ISSUES_REPORTED_DASHBOARD_SCREEN',
  ASSOCIATION_ISSUES_REPORTED_DETAIL_SCREEN: 'ASSOCIATION_ISSUES_REPORTED_DETAIL_SCREEN',
  ASSOCIATION_MESSAGES_DASHBOARD_SCREEN: 'ASSOCIATION_MESSAGES_DASHBOARD_SCREEN',
  ASSOCIATION_MESSAGES_DETAIL_SCREEN: 'ASSOCIATION_MESSAGES_DETAIL_SCREEN',
  SHOW_VIEW_PDF_SCREEN: 'SHOW_VIEW_PDF_SCREEN',
  
  HOME_SCREEN: 'HOME',
  PROFILE_SCREEN: 'STUDENTS',
  NOTIFICATION_SCREEN: 'NOTIFICATIONS',

  CHARGE_DETAIL_SCREEN: 'CHARGE_DETAIL_SCREEN',
  NOC_MOVE_IN_SCREEN: 'NOC_MOVE_IN_SCREEN',
  NOC_MOVE_IN_DASHBOARD_SCREEN: 'NOC_MOVE_IN_DASHBOARD_SCREEN',
  NOC_MOVE_IN_EDIT_SCREEN: 'NOC_MOVE_IN_EDIT_SCREEN',
  NOC_MOVE_OUT_SCREEN: 'NOC_MOVE_OUT_SCREEN',
  NOC_MOVE_OUT_DASHBOARD_SCREEN: 'NOC_MOVE_OUT_DASHBOARD_SCREEN',
  NOC_MOVE_OUT_EDIT_SCREEN: 'NOC_MOVE_OUT_EDIT_SCREEN',
  MESSAGES_SCREEN: 'MESSAGES_SCREEN',
  MESSAGES_DASHBOARD: 'MESSAGES_DASHBOARD',
  MESSAGES_DETAIL_SCREEN: 'MESSAGES_DETAIL_SCREEN',
  NOC_MAINTENANCE_DASHBOARD_SCREEN: 'NOC_MAINTENANCE_DASHBOARD_SCREEN',
  NOC_MAINTENANCE_EDIT_SCREEN: 'NOC_MAINTENANCE_EDIT_SCREEN',
  NOC_MAINTENANCE_SCREEN: 'NOC_MAINTENANCE_SCREEN',
  REPORT_ISSUES_SCREEN: 'REPORT_ISSUES_SCREEN',
  REPORT_ISSUES_DASHBOARD_SCREEN: 'REPORT_ISSUES_DASHBOARD_SCREEN',
  REPORT_ISSUES_DETAIL_SCREEN: 'REPORT_ISSUES_DETAIL_SCREEN',
  SETTINGS_SCREEN: 'SETTINGS_SCREEN',
  MOVE_RESPONSE_SCREEN: 'MOVE_RESPONSE_SCREEN',

  //Access Card
  ACCESS_CARD_DASHBOARD: 'ACCESS_CARD_DASHBOARD',
  ACCESS_CARD_ADD: 'ACCESS_CARD_ADD',

  //AC Maintenance
  AC_MAINTENANCE_DASHBOARD: 'AC_MAINTENANCE_DASHBOARD',
  AC_MAINTENANCE_ADD: 'AC_MAINTENANCE_ADD',

  //Security Role
  SECURITY_HOME_STACK: 'SECURITY_HOME_STACK',

  //home
  SECURITY_HOME_SCREEN: 'SECURITY_HOME_SCREEN',
  //Visit entry
  SECURITY_VISIT_ENTRY_HOME: 'SECURITY_VISIT_ENTRY_HOME',
  SECURITY_VISIT_EDIT: 'SECURITY_VISIT_EDIT',
  SECURITY_VISIT_ADD: 'SECURITY_VISIT_ADD',
  //Archive Request
  SECURITY_ARCHIVE_HOME: 'SECURITY_ARCHIVE_HOME',
  SECURITY_ARCHIVE_DETAIL: 'SECURITY_ARCHIVE_DETAIL',
};

export default Routes;
